START_CONTENT_PAGE = 5
END_CONTENT_PAGE = 8
START_UNIT_PAGE = 14
END_UNIT_PAGE = 303
START_ANSWER_PAGE = 348
END_ANSWER_PAGE = 379

EXERCISE_CROP_TOP = 230
EXERCISE_CROP_BOTTOM = 140
EXERCISE_CROP_LEFT = 225
EXERCISE_CROP_RIGHT = 110

EXERCISE_SEARCH_WIDTH_RATIO = 0.4
EXERCISE_BOX_MIN_WIDTH = 30
EXERCISE_BOX_MAX_WIDTH = 80
EXERCISE_BOX_MIN_HEIGHT = 20
EXERCISE_BOX_MAX_HEIGHT = 60
