START_CONTENT_PAGE = 5
END_CONTENT_PAGE = 8
START_UNIT_PAGE = 14
END_UNIT_PAGE = 303
START_ANSWER_PAGE = 348
END_ANSWER_PAGE = 379

EXERCISE_CROP_TOP = 230
EXERCISE_CROP_BOTTOM = 140
EXERCISE_CROP_LEFT = 225
EXERCISE_CROP_RIGHT = 110

EXERCISE_SEARCH_WIDTH_RATIO = 0.07
EXERCISE_BOX_MIN_WIDTH = 110
EXERCISE_BOX_MAX_WIDTH = 140
EXERCISE_BOX_MIN_HEIGHT = 60
EXERCISE_BOX_MAX_HEIGHT = 80

EXERCISE_HSV_LOWER_HUE = 80
EXERCISE_HSV_LOWER_SAT = 60
EXERCISE_HSV_LOWER_VAL = 80
EXERCISE_HSV_UPPER_HUE = 100
EXERCISE_HSV_UPPER_SAT = 255
EXERCISE_HSV_UPPER_VAL = 255

EXERCISE_KERNEL_SIZE = 5
EXERCISE_DILATE_ITERATIONS = 1
EXERCISE_ERODE_ITERATIONS = 1

EXERCISE_MIN_AREA = 7000
EXERCISE_PADDING = 10
EXERCISE_MIN_HEIGHT = 30

# Constants for white space detection at bottom
BOTTOM_WHITE_SEARCH_HEIGHT_RATIO = 0.3
BOTTOM_WHITE_THRESHOLD = 250
BOTTOM_WHITE_MIN_RATIO = 0.98
BOTTOM_WHITE_MARGIN = 15
